### ISSUE TITLE
unstable optimization in inversion

### ISSUE THREAD

**Issue by yaseryacoob** [snap-research/weights2weights#1]
Thanks for sharing your work. In looking at the loss in invresion.py I noticed that the optimization is not stable, even when I allowed for 1000 iterations. You can see the model_pred (just 3 out of 4 channels) display every 100 epochs and the loss recorded. in this series of images (using your example). The final loss at 999 was 0.040231965482234955.
![values](https://github.com/user-attachments/assets/676b644c-524f-48ba-af08-682c1799e546)

 
![NOISED_0_loss_0 002037961967289448](https://github.com/user-attachments/assets/283cc0de-555f-4695-a01f-52847bfd3e35)
![NOISED_100_loss_0 07902728021144867](https://github.com/user-attachments/assets/0044ba7f-9b26-43fd-b4d5-9effcc105b19)
![NOISED_200_loss_0 4763336181640625](https://github.com/user-attachments/assets/f05f09f9-c803-4ca4-b144-4ed3eeb5cbc0)
![NOISED_300_loss_0 042885422706604004](https://github.com/user-attachments/assets/4a875c7d-010d-4b45-a0f7-9fc0cceaf8b2)
![NOISED_400_loss_0 08340265601873398](https://github.com/user-attachments/assets/f2e6643e-7c6d-4414-af4d-ba5e38e3cab7)
![NOISED_500_loss_0 08626551926136017](https://github.com/user-attachments/assets/b76dd336-f53e-4c68-b514-28a74ae6357b)
![NOISED_600_loss_0 07441602647304535](https://github.com/user-attachments/assets/c3ac229b-4be2-4729-8bfa-75a0266b00e6)
![NOISED_700_loss_0 36750757694244385](https://github.com/user-attachments/assets/27619e2e-4ecc-4d8f-ba45-b0a19746c46d)
![NOISED_800_loss_0 36185115575790405](https://github.com/user-attachments/assets/ff19c0fa-105f-4e40-94a1-d2b877452902)
![NOISED_900_loss_0 008720280602574348](https://github.com/user-attachments/assets/4785fbf8-3b67-4e73-a110-4de6ae9ce47f)

**Comment by avdravid** [comment]
Hi. Thank you for posting your issue. The loss landscape of diffusion models is very noisy, so you cannot really get anything meaningful by just looking at the loss at each iteration. You would get this similar noisy optimization if you were doing standard Dreambooth or fine-tuning. The best thing is to check what the generated samples look like. Let me know if you need any further guidance.
