### ISSUE TITLE
Do you have code on how did you train the linear classifier?

### ISSUE THREAD

**Issue by iszihan** [snap-research/weights2weights#7]
As question says.

**Comment by avdravid** [comment]
The linear classifier is solved via least squares at this code snippet: https://github.com/snap-research/weights2weights/blob/76f0bde99ab8e48a25d825f202115300aef8efc3/editing.py#L43C1-L44C1

The pseudoinverse is precomputed and we provide the file at https://huggingface.co/snap-research/weights2weights. It can also be calculated use the proj_1000.pt file by computing torch.inverse(A.T@A)@A.T
