### ISSUE TITLE
Missing File: ../output/real_inversion_w2w/w2wmodel.pt in identity_editing.ipynb

### ISSUE THREAD

**Issue by omertalmi5** [snap-research/weights2weights#8]
Hi, I am trying to run the identity_editing.ipynb notebook, but I'm unable to locate the file:
../output/real_inversion_w2w/w2wmodel.pt
Could you please provide guidance on where to find this file or suggest an alternative file I can use instead?
Thanks in advance!

**Comment by avdravid** [comment]
Hi! Thank you for your question. That is just a placeholder for some model that can be loaded in. You can either run the inversion notebook to get a model that you can load in and edit, or you can sample a new model in the sampling notebook and save that, load it in, then edit.
