### ISSUE TITLE
face mask

### ISSUE THREAD

**Issue by luchaoqi** [snap-research/weights2weights#9]
Hello, 

Do you have the code to get the face mask for inversion? basically the mask for `invert.py`
```
    parser.add_argument("--mask_path", default=None, type=str, help="Path to mask file.")
```

I see you have a pair of input and mask in your `inversion/images/real_image/`. How did you get the mask?

**Comment by avdravid** [comment]
Hi! The mask is not necessary but it does improve performance. You can use Segment Anything to obtain a mask of the head. An example notebook can be found here: https://drive.google.com/file/d/1BxjYMkcoMEo_N_gvD8aMUUIE2g_B5ZQa/view?usp=sharing. 

You can also manually draw a mask in our demo at: https://huggingface.co/spaces/snap-research/weights2weights
